"""
Django settings for teste_django project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f$v=e=-9c-1&b)fskdf-isz5c(p=t!g%+6bg*txhjf6gp$u$ll'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ==============================================================================
# CONFIGURAÇÕES PARA O TESTE NO CELULAR (NGROK / WI-FI)
# ==============================================================================

# 1. Permite que o servidor seja acessado por qualquer endereço (IP ou Ngrok)
ALLOWED_HOSTS = ['*']

# 2. Permite que o formulário seja salvo vindo de um endereço seguro do Ngrok
# Sem isso, ao clicar em "Salvar" no celular, daria erro de "CSRF Verification Failed"
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://semiacademic-sightless-hoa.ngrok-free.dev',
]

# ==============================================================================


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Meus Apps (Adicione estas linhas)
    'core',
    'cadastros',
    'financeiro',
    'workflow',
    'import_export',
    'rangefilter'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'teste_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teste_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'  # <--- Mude de 'en-us' para 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'  # <--- Mude de 'UTC' para seu fuso horário

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# teste_django/settings.py

STATICFILES_DIRS = [BASE_DIR / "static"]

# CONFIGURAÇÃO CRÍTICA PARA USAR O NOVO MODELO DE USUÁRIO
AUTH_USER_MODEL = 'core.UsuarioCustomizado'

# Final do arquivo settings.py

# O CÓDIGO ABAIXO É O QUE TRATA DO VISUAL DO SISTEMA

JAZZMIN_SETTINGS = {
    # Logo do Menu Lateral (quando logado)
    "site_logo": "img/logo.jpg",

    # Logo da Tela de Login (aquela grandona)
    # CORRIGIDO: Estava .png, mudei para .jpg
    "login_logo": "img/logo.jpg",

    # Classe CSS para ajustar tamanho
    # CORRIGIDO: Mudei de 'img-circle' para 'img-fluid' para não cortar as bordas
    "site_logo_classes": "img-fluid",

    # Título na aba do navegador
    "site_title": "Malupe Admin",

    # Título no topo do menu de login
    "site_header": "Malupe",

    # Título na marca (canto superior esquerdo)
    # CORRIGIDO: Mudei de 'python' para o nome da empresa
    "site_brand": "Painel Malupe",

    # Mensagem de boas-vindas na tela de login
    "welcome_sign": "Acesso do Colaborador Malupe",

    # Copyright no rodapé
    "copyright": "Malupe Ltda",

    # Pesquisa geral no menu lateral (procura em tudo)
    "search_model": ["financeiro.ContasAPagar", "cadastros.Cliente"],

    "custom_css": "css/admin_custom.css",

    # Ícones para os menus (opcional - usa FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "cadastros.Cliente": "fas fa-user-tie",
        "cadastros.Fornecedor": "fas fa-truck",
        "financeiro.ContasAPagar": "fas fa-money-bill-wave",
        "financeiro.ContasAReceber": "fas fa-hand-holding-usd",
        "financeiro.BaseSaldo": "fas fa-chart-line",
        "workflow.Despesa": "fas fa-tasks",
    },

    # --- A FERRAMENTA MÁGICA DE CUSTOMIZAÇÃO ---
    "show_ui_builder": True,
}