# Generated by Django 5.2.2 on 2026-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturasRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Coberturas de Falta',
                'verbose_name_plural': 'Coberturas de Falta',
                'managed': False,
            },
        ),
    ]
