# Generated by Django 5.2.2 on 2026-07-03 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_colaboradorinfo_options_and_more'),
        ('monitoramento_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal')], max_length=10, verbose_name='Periodicidade')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tomador', verbose_name='Tomador')),
            ],
            options={
                'verbose_name': 'Folha',
                'verbose_name_plural': 'Folhas',
                'ordering': ['tomador__nome', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ColaboradorInformal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.PositiveIntegerField(verbose_name='Qt')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('registro', models.BooleanField(default=False, verbose_name='Registro')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco (depósito)')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(max_length=30, verbose_name='Conta')),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo na folha')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.filial', verbose_name='Filial')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='monitoramento_rh.folha', verbose_name='Folha')),
            ],
            options={
                'verbose_name': 'Colaborador Informal',
                'verbose_name_plural': 'Colaboradores Informais',
                'ordering': ['banco', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Competência início')),
                ('data_fim', models.DateField(verbose_name='Competência fim')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada para aprovação'), ('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='monitoramento_rh.folha', verbose_name='Folha')),
            ],
            options={
                'verbose_name': 'Pagamento de Folha',
                'verbose_name_plural': 'Pagamentos de Folha',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor anterior')),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor atual')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa da diferença')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoramento_rh.colaboradorinformal', verbose_name='Colaborador')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='monitoramento_rh.pagamentofolha', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Item de Pagamento',
                'verbose_name_plural': 'Itens de Pagamento',
                'ordering': ['colaborador__banco', 'colaborador__nome'],
            },
        ),
    ]
