# Generated by Django 5.2.2 on 2026-07-03 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_colaboradorinfo_options_and_more'),
        ('monitoramento_rh', '0002_folha_colaboradorinformal_pagamentofolha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folha',
            name='empresa_pagadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa Pagadora'),
        ),
        migrations.AddField(
            model_name='folha',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Fornecedor (contábil)'),
        ),
        migrations.AddField(
            model_name='folha',
            name='plano_de_contas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.planodecontas', verbose_name='Plano de Contas'),
        ),
        migrations.AddField(
            model_name='pagamentofolha',
            name='aprovado_rh_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentofolha',
            name='aprovado_rh_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado (RH) por'),
        ),
        migrations.AddField(
            model_name='pagamentofolha',
            name='banco_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.banco', verbose_name='Banco de Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamentofolha',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pago por'),
        ),
    ]
