# Generated by Django 5.2.2 on 2026-08-13 14:38

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_rh', '0003_folha_empresa_pagadora_folha_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorinformal',
            name='cpf',
            field=models.CharField(max_length=14, validators=[cadastros.models.validar_cpf], verbose_name='CPF'),
        ),
    ]
