# Generated by Django 6.0 on 2025-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(max_length=20, unique=True, verbose_name='CNPJ ou CPF')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia de Vencimento (01-31)')),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Contrato')),
                ('descricao_atividade', models.TextField(blank=True, verbose_name='Descrição da Atividade')),
                ('forma_recebimento', models.CharField(max_length=100, verbose_name='Forma de Recebimento')),
                ('tipo', models.CharField(choices=[('FIXO', 'Fixo'), ('EVENTUAL', 'Eventual')], default='EVENTUAL', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Filial')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ (Opcional)')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(max_length=20, unique=True, verbose_name='CNPJ ou CPF')),
                ('forma_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Forma de Pagamento')),
                ('conta_contabil', models.CharField(blank=True, max_length=50, verbose_name='Conta Contábil')),
                ('letra_acesso', models.CharField(default='A', max_length=5, verbose_name='Letra de Acesso (Ex: A)')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='MotivoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Motivo da Ausência')),
            ],
            options={
                'verbose_name': 'Motivo de Ausência',
                'verbose_name_plural': 'Motivos de Ausência',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Tomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tomador',
                'verbose_name_plural': 'Tomadores',
            },
        ),
    ]
