# Generated by Django 6.0 on 2025-12-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipo de Servico', 'verbose_name_plural': 'Tipos de Servicos'},
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo de Servico'),
        ),
    ]
