# Generated by Django 6.0 on 2026-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial'),
        ),
    ]
