# Generated by Django 5.2.2 on 2026-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_add_plano_de_contas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de Vencimento (01-31)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Contrato'),
        ),
    ]
