# Generated by Django 5.2.2 on 2026-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_cliente_cnpj_optional_contrato_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('tipo_pix', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('TELEFONE', 'Telefone'), ('EMAIL', 'E-mail'), ('ALEATORIA', 'Chave Aleatória'), ('BANCO', 'Dados Bancários')], max_length=10, verbose_name='Tipo de Chave')),
                ('chave_pix', models.CharField(blank=True, max_length=200, verbose_name='Chave Pix / Dados Bancários')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Colaborador Info',
                'verbose_name_plural': 'Colaboradores Info',
                'ordering': ['nome'],
            },
        ),
    ]
