# Generated by Django 5.2.2 on 2026-07-03 17:48

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_add_colaboradorinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorinfo',
            options={'ordering': ['nome'], 'verbose_name': 'Cad. Folguista', 'verbose_name_plural': 'Cad. Folguistas'},
        ),
        migrations.AlterModelOptions(
            name='motivoausencia',
            options={'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
        migrations.AlterField(
            model_name='colaboradorinfo',
            name='cpf',
            field=models.CharField(max_length=20, validators=[cadastros.models.validar_cpf], verbose_name='CPF'),
        ),
    ]
