# Generated by Django 5.2.2 on 2026-07-10 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_colaboradorinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.filial', verbose_name='Filial'),
        ),
    ]
