# Generated by Django 5.2.2 on 2026-07-22 13:41

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_add_filial_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='entra_no_saldo_geral',
            field=models.BooleanField(default=True, help_text='Se desmarcado, a conta continua ativa no sistema mas não soma no card de Saldo Geral do dashboard.', verbose_name='Entra no Saldo Geral'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, validators=[cadastros.models.validar_cpf]),
        ),
    ]
