# Generated by Django 5.2.2 on 2026-08-13 19:33

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_add_entra_no_saldo_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorinfo',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, validators=[cadastros.models.validar_cpf], verbose_name='CPF'),
        ),
    ]
