# Generated by Django 5.2.2 on 2026-09-03 19:54

from django.db import migrations, models


def copiar_flag_existente(apps, schema_editor):
    # Preserva o comportamento já em vigor: bancos com "Entra no Saldo
    # Geral" desmarcado (ex.: CAIXINHA) já estavam escondidos das novas
    # Contas a Pagar/Receber — sem isso, essa migração reapareceria com
    # eles disponíveis de novo (o default do campo novo é True).
    Banco = apps.get_model('cadastros', 'Banco')
    for banco in Banco.objects.all():
        banco.disponivel_para_movimentacao = banco.entra_no_saldo_geral
        banco.save(update_fields=['disponivel_para_movimentacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_colaboradorinfo_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='disponivel_para_movimentacao',
            field=models.BooleanField(default=True, help_text="Se desmarcado, a conta não aparece mais como opção ao criar novas Contas a Pagar/Receber. Independente de 'Entra no Saldo Geral' — dá pra esconder do dashboard sem tirar da movimentação, e vice-versa.", verbose_name='Disponível para Movimentação'),
        ),
        migrations.RunPython(copiar_flag_existente, migrations.RunPython.noop),
    ]
