# Generated by Django 6.0 on 2025-12-22 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('financeiro', '0004_alter_basesaldo_options_alter_contasapagar_options_and_more'),
        ('workflow', '0007_alter_despesa_status_alter_despesa_tipo_lancamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Nota Fiscal')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Data da Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('tipo_fixo', models.CharField(default='Extra', editable=False, max_length=50, verbose_name='Tipo')),
                ('valor_recebimento', models.DecimalField(decimal_places=2, help_text='Valor que entrará no Contas a Receber', max_digits=10, verbose_name='Valor (Receita)')),
                ('inicio_cobertura', models.DateField(blank=True, null=True, verbose_name='Início Cobertura')),
                ('fim_cobertura', models.DateField(blank=True, null=True, verbose_name='Fim Cobertura')),
                ('nome_cobriu', models.CharField(blank=True, max_length=150, verbose_name='Nome de Quem Cobriu')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BANCO', 'Transferência Bancária')], max_length=10, verbose_name='Forma Pagamento')),
                ('dados_bancarios_pagto', models.TextField(blank=True, verbose_name='Dados para Pagamento')),
                ('administrativo', models.ForeignKey(limit_choices_to={'groups__name': 'Administrativo'}, on_delete=django.db.models.deletion.PROTECT, related_name='extras_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Administrativo (Aprovador)')),
                ('colaborador_faltou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.colaborador', verbose_name='Colaborador que Faltou')),
                ('conta_receber_criada', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contasareceber')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.filial', verbose_name='Filial')),
                ('motivo_ausencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.motivoausencia', verbose_name='Motivo Ausência')),
                ('tomador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.tomador', verbose_name='Tomador')),
                ('workflow_criado', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentoextra', to='workflow.despesa')),
            ],
            options={
                'verbose_name': 'Lançamento de Extra',
                'verbose_name_plural': 'Lançamentos de Extras',
            },
        ),
    ]
