# Generated by Django 6.0 on 2025-12-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoextra',
            name='banco_recebimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.banco', verbose_name='Banco de Recebimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamentoextra',
            name='empresa_prestadora',
            field=models.ForeignKey(default=1, help_text='Empresa do Grupo que receberá o valor', on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa Prestadora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamentoextra',
            name='valor_recebimento',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (Receita)'),
        ),
    ]
