# Generated by Django 6.0 on 2025-12-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('extras', '0002_lancamentoextra_banco_recebimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentoextra',
            name='dados_bancarios_pagto',
        ),
        migrations.RemoveField(
            model_name='lancamentoextra',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='lancamentoextra',
            name='nome_cobriu',
        ),
        migrations.AlterField(
            model_name='lancamentoextra',
            name='banco_recebimento',
            field=models.ForeignKey(limit_choices_to=models.Q(('nome__contains', '(AUTO)'), _negated=True), on_delete=django.db.models.deletion.PROTECT, to='cadastros.banco', verbose_name='Banco de Recebimento'),
        ),
        migrations.AlterField(
            model_name='lancamentoextra',
            name='empresa_prestadora',
            field=models.ForeignKey(help_text='Empresa do Grupo que receberá o valor', limit_choices_to=models.Q(('nome__contains', '(AUTO)'), _negated=True), on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa Prestadora'),
        ),
        migrations.AlterField(
            model_name='lancamentoextra',
            name='motivo_ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.motivoausencia', verbose_name='Motivo'),
        ),
    ]
