# Generated by Django 5.2.2 on 2026-06-17 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_remove_lancamentoextra_dados_bancarios_pagto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentoextra',
            name='dias_cobertura',
            field=models.TextField(blank=True, help_text='Datas separadas por vírgula: 2026-06-01,2026-06-05', verbose_name='Dias de Cobertura'),
        ),
        migrations.AlterField(
            model_name='lancamentoextra',
            name='administrativo',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Administrativo'), ('groups__name', 'Aprovador RH'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='extras_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Aprovador)'),
        ),
    ]
