# Generated by Django 6.0 on 2025-12-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(auto_now_add=True, verbose_name='Data de Lançamento')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento Original')),
                ('numero_nota', models.CharField(max_length=50, verbose_name='Nº da Nota/ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social (Cliente/Fornecedor)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (+Entrada, -Saída)')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('status_despesa', models.CharField(max_length=50, verbose_name='Status da Despesa (Pago/Recebido)')),
            ],
            options={
                'verbose_name': 'Base de Saldo (Ledger)',
                'verbose_name_plural': 'Base de Saldos (Ledger)',
                'ordering': ['data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='ContasAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('nota', models.CharField(max_length=50, unique=True, verbose_name='Nº da Nota Fiscal')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('conta_contabil', models.CharField(blank=True, max_length=50, verbose_name='Conta Contábil')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data de Baixa/Pagamento')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.banco', verbose_name='Banco de Pagamento')),
                ('empresa_pagadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa Pagadora')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='ContasAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('nota', models.CharField(max_length=50, unique=True, verbose_name='Nº da Nota Fiscal')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('escala_horas', models.CharField(blank=True, max_length=50, verbose_name='Escala de Horas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data de Baixa/Recebimento')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.banco', verbose_name='Banco de Recebimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente', verbose_name='Cliente')),
                ('empresa_prestadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa Prestadora')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
    ]
