# Generated by Django 6.0 on 2025-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=5, unique=True, verbose_name='Prefixo')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='Último Número Gerado')),
            ],
            options={
                'verbose_name': 'Contador Sequencial',
                'verbose_name_plural': 'Contadores Sequenciais',
            },
        ),
    ]
