# Generated by Django 6.0 on 2025-12-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_sequencial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasapagar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contasareceber',
            options={},
        ),
    ]
