# Generated by Django 6.0 on 2025-12-10 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_contasapagar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basesaldo',
            options={'ordering': ['-data_baixa'], 'verbose_name': 'Base de Saldo (Extrato)', 'verbose_name_plural': 'Base de Saldos (Extrato)'},
        ),
        migrations.AlterModelOptions(
            name='contasapagar',
            options={'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='contasareceber',
            options={'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.RemoveField(
            model_name='basesaldo',
            name='data_lancamento',
        ),
        migrations.RemoveField(
            model_name='basesaldo',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='basesaldo',
            name='numero_nota',
        ),
        migrations.RemoveField(
            model_name='basesaldo',
            name='razao_social',
        ),
        migrations.RemoveField(
            model_name='basesaldo',
            name='status_despesa',
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='data_baixa',
            field=models.DateField(null=True, verbose_name='Data Baixa'),
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='data_emissao',
            field=models.DateField(default='2025-01-01', verbose_name='Emissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='id_origem',
            field=models.IntegerField(default=0, verbose_name='ID Original'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='nome',
            field=models.CharField(default='SISTEMA', max_length=200, verbose_name='Nome (Forn/Cli)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='origem',
            field=models.CharField(default='SISTEMA', max_length=10, verbose_name='Origem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='status',
            field=models.CharField(default='SISTEMA', max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='usuario_baixa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuário que Baixou'),
        ),
        migrations.AddField(
            model_name='basesaldo',
            name='vencimento',
            field=models.DateField(default='2025-01-01', verbose_name='Vencimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='usuario_baixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Baixa'),
        ),
        migrations.AddField(
            model_name='contasareceber',
            name='usuario_baixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Baixa'),
        ),
        migrations.AlterField(
            model_name='basesaldo',
            name='empresa',
            field=models.CharField(max_length=200, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='basesaldo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Líquido'),
        ),
    ]
