# Generated by Django 6.0 on 2026-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_basesaldo_options_alter_contasapagar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerarFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Gerar Fixos Mensal',
                'verbose_name_plural': 'Gerar Fixos Mensais',
                'managed': False,
            },
        ),
    ]
