# Generated by Django 6.0 on 2026-05-30 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_banco_saldo_inicial'),
        ('financeiro', '0005_gerarfixo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerarfixo',
            options={'managed': False, 'verbose_name': 'Gerar Fixo Mensal', 'verbose_name_plural': 'Gerar Fixos Mensais'},
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Transferência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('banco_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='cadastros.banco', verbose_name='Banco de Destino')),
                ('banco_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to='cadastros.banco', verbose_name='Banco de Origem')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
            },
        ),
    ]
