# Generated by Django 6.0 on 2026-05-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_banco_saldo_inicial'),
        ('financeiro', '0006_alter_gerarfixo_options_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='classificacao',
            field=models.CharField(choices=[('DEFINITIVA', '✅ Definitiva (Fica lá)'), ('TEMPORARIA', '⚠️ Temporária (A Devolver)')], default='DEFINITIVA', max_length=15, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='instrucao_retorno',
            field=models.TextField(blank=True, help_text='Preencha apenas para transferências temporárias.', verbose_name='Instruções de Retorno'),
        ),
    ]
