# Generated by Django 6.0 on 2026-05-31 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_banco_saldo_inicial'),
        ('financeiro', '0007_transferencia_classificacao_transferencia_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='classificacao',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='data_devolucao',
            field=models.DateField(blank=True, help_text='Preenchida automaticamente ao marcar como Devolvida.', null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='status',
            field=models.CharField(choices=[('DEFINITIVA', '🟢 Definitiva'), ('TEMP_PENDENTE', '🟡 Temporária (Pendente de Devolução)'), ('TEMP_DEVOLVIDA', '🔵 Temporária (Devolvida)'), ('CANCELADA', '⚫ Cancelada')], default='DEFINITIVA', max_length=20, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='banco_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='cadastros.banco', verbose_name='Banco de Destino (Entrou)'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='banco_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to='cadastros.banco', verbose_name='Banco de Origem (Saiu)'),
        ),
    ]
