# Generated by Django 6.0 on 2026-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_remove_transferencia_classificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='data_prevista_retorno',
            field=models.DateField(blank=True, help_text='Obrigatório para transferências temporárias.', null=True, verbose_name='Data Prevista de Retorno'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_devolucao',
            field=models.DateField(blank=True, help_text='Preenchida automaticamente ao marcar como Devolvida.', null=True, verbose_name='Data de Devolução Efetiva'),
        ),
    ]
