# Generated by Django 5.2.2 on 2026-06-11 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_add_responsavel_pagamento_contasapagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.CreateModel(
            name='CicloSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('LIVRE', 'Livre')], default='SEMANAL', max_length=10, verbose_name='Período')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Fechamento')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
            options={
                'verbose_name': 'Ciclo de Supervisores',
                'verbose_name_plural': 'Ciclos de Supervisores',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SaldoSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponível')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='financeiro.ciclosupervisor', verbose_name='Ciclo')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Saldo do Supervisor',
                'verbose_name_plural': 'Saldos dos Supervisores',
                'unique_together': {('ciclo', 'supervisor')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito (Saldo)'), ('DEBITO', 'Débito (Utilização)')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('referencia_despesa_id', models.IntegerField(blank=True, null=True, verbose_name='Ref. Despesa Workflow (ID)')),
                ('referencia_cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contasapagar', verbose_name='Ref. Contas a Pagar')),
                ('saldo_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.saldosupervisor', verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimentação do Supervisor',
                'verbose_name_plural': 'Movimentações do Supervisor',
                'ordering': ['-data'],
            },
        ),
    ]
