# Generated by Django 5.2.2 on 2026-06-11 19:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_contasapagar_supervisor_ciclosupervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaosupervisor',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='saldosupervisor',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Saldo Supervisor', 'verbose_name_plural': 'Saldo Supervisores'},
        ),
        migrations.AlterUniqueTogether(
            name='saldosupervisor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saldosupervisor',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Fechamento'),
        ),
        migrations.AddField(
            model_name='saldosupervisor',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='saldosupervisor',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por'),
        ),
        migrations.AddField(
            model_name='saldosupervisor',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Inicial'),
        ),
        migrations.AddField(
            model_name='saldosupervisor',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status'),
        ),
        migrations.RemoveField(
            model_name='saldosupervisor',
            name='ciclo',
        ),
        migrations.DeleteModel(
            name='CicloSupervisor',
        ),
    ]
