# Generated by Django 5.2.2 on 2026-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_redesign_saldo_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldosupervisor',
            name='saldo_inicial',
        ),
        migrations.AddField(
            model_name='saldosupervisor',
            name='numero',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Nº'),
        ),
    ]
