# Generated by Django 5.2.2 on 2026-06-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_add_numero_remove_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldosupervisor',
            name='observacao_fechamento',
            field=models.TextField(blank=True, verbose_name='Observações do Fechamento'),
        ),
    ]
