# Generated by Django 5.2.2 on 2026-06-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_add_plano_de_contas'),
        ('financeiro', '0014_add_observacao_fechamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contasapagar',
            name='conta_contabil',
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='plano_de_contas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.planodecontas', verbose_name='Plano de Contas'),
        ),
    ]
