# Generated by Django 5.2.2 on 2026-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_plano_de_contas_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldosupervisor',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10, verbose_name='Status'),
        ),
    ]
