# Generated by Django 5.2.2 on 2026-07-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_colaboradorinfo_options_and_more'),
        ('financeiro', '0016_add_cancelado_status_saldosupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
