# Generated by Django 6.0 on 2025-12-09 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('financeiro', '0003_alter_contasapagar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão da Nota')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto (Em Análise RH)'), ('APROVADO_RH', 'Aprovado RH / Pendente Financeiro'), ('REPROVADO_RH', 'Reprovado pelo RH'), ('APROVADO_FIN', 'Aprovado Financeiro / Próximo Pagamento'), ('REPROVADO_FIN', 'Reprovado pelo Financeiro'), ('PAGO', 'Pago e Baixado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status do Workflow')),
                ('data_aprovacao_rh', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_fin', models.DateTimeField(blank=True, null=True)),
                ('aprovador_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_aprovadas_fin', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Financeiro')),
                ('aprovador_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_aprovadas_rh', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador RH')),
                ('colaborador_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.colaborador', verbose_name='Colaborador Solicitante')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contasapagar', verbose_name='Conta Pagar Relacionada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa Pagadora')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Despesa (Workflow)',
                'verbose_name_plural': 'Despesas (Workflow)',
            },
        ),
    ]
