# Generated by Django 6.0 on 2025-12-15 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name': 'Workflow de Despesa', 'verbose_name_plural': 'Workflow de Despesas'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='aprovador_fin',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='aprovador_rh',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='colaborador_solicitante',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='conta_pagar',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_aprovacao_fin',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_aprovacao_rh',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='vencimento',
        ),
        migrations.AddField(
            model_name='despesa',
            name='banco_pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.banco', verbose_name='Banco Pagador'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='colaborador_faltou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faltas', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador que Faltou'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante (Upload)'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='dados_bancarios_pagto',
            field=models.TextField(blank=True, verbose_name='Dados para Pagamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Despesa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_ultima_alteracao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Alteração'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='empresa_pagadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.empresa', verbose_name='Empresa Pagadora'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='filial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='fim_cobertura',
            field=models.DateField(blank=True, null=True, verbose_name='Fim Cobertura'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BANCO', 'Transferência Bancária')], max_length=10, verbose_name='Forma Pagamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='inicio_cobertura',
            field=models.DateField(blank=True, null=True, verbose_name='Início Cobertura'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='motivo_ausencia',
            field=models.CharField(blank=True, choices=[('FERIAS', 'Férias'), ('ATESTADO', 'Atestado Médico'), ('FOLGA', 'Folga'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Motivo Ausência'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='nome_cobriu',
            field=models.CharField(blank=True, max_length=150, verbose_name='NOME DE QUEM COBRIU'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='operador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_operador', to=settings.AUTH_USER_MODEL, verbose_name='Operador Responsável'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo_lancamento',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tomador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tomador_set', to='cadastros.empresa', verbose_name='Tomador/Cliente'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho (Solicitante)'), ('AGUARDANDO_RH', 'Aguardando RH'), ('CANCELADO_RH', 'Cancelado pelo RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('CANCELADO_FIN', 'Cancelado pelo Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador'), ('PAGO', 'Pago / Finalizado'), ('CANCELADO_OP', 'Cancelado pelo Operador')], default='RASCUNHO', max_length=20, verbose_name='Status Atual'),
        ),
        migrations.CreateModel(
            name='LogWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_usuario', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.despesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
