# Generated by Django 6.0 on 2025-12-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('workflow', '0002_alter_despesa_options_remove_despesa_aprovador_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name': 'Nova Solicitação / Caixinha', 'verbose_name_plural': 'Workflow de Despesas'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='operador_responsavel',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='colaborador_faltou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faltas_workflow', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador que Faltou'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Nome Despesa / Fornecedor'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador'), ('PAGO', 'Pago / Finalizado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_lancamento',
            field=models.CharField(choices=[('CAIXINHA', 'Caixinha'), ('SOLICITACAO', 'Solicitação')], default='CAIXINHA', max_length=20, verbose_name='Tipo de Lançamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tomador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tomador_workflow', to='cadastros.empresa', verbose_name='Tomador'),
        ),
    ]
