# Generated by Django 6.0 on 2025-12-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('workflow', '0003_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name': 'Workflow de Despesa', 'verbose_name_plural': 'Workflow de Despesas'},
        ),
        migrations.AlterField(
            model_name='despesa',
            name='colaborador_faltou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faltas_workflow', to='cadastros.colaborador', verbose_name='Colaborador que Faltou'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='motivo_ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.motivoausencia', verbose_name='Motivo Ausência'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_lancamento',
            field=models.CharField(choices=[('CAIXINHA', 'Caixinha'), ('SOLICITACAO', 'Solicitação')], default='CAIXINHA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tomador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.tomador', verbose_name='Tomador'),
        ),
    ]
