# Generated by Django 6.0 on 2025-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='nome_cobriu',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome de Quem Cobriu'),
        ),
    ]
