# Generated by Django 6.0 on 2025-12-16 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_despesa_nome_cobriu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_operador', to=settings.AUTH_USER_MODEL, verbose_name='Selecione o Operador'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador'), ('PAGO', 'Pago / Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_RH', max_length=20, verbose_name='Status Atual'),
        ),
    ]
