# Generated by Django 6.0 on 2025-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_despesa_operador_alter_despesa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_ADM', 'Aguardando Administrativo'), ('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador'), ('PAGO', 'Pago / Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_RH', max_length=20, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_lancamento',
            field=models.CharField(choices=[('CAIXINHA', 'Caixinha'), ('SOLICITACAO', 'Solicitação'), ('EXTRA', 'Extra')], default='CAIXINHA', max_length=20, verbose_name='Tipo'),
        ),
    ]
