# Generated by Django 6.0 on 2025-12-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('workflow', '0007_alter_despesa_status_alter_despesa_tipo_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BANCO', 'Transferência Bancária'), ('DINHEIRO', 'Dinheiro')], max_length=10, verbose_name='Forma Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='motivo_ausencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.motivoausencia', verbose_name='Motivo'),
        ),
    ]
