# Generated by Django 6.0 on 2025-12-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_alter_despesa_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='dados_bancarios_pagto',
            field=models.TextField(blank=True, null=True, verbose_name='Dados para Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BANCO', 'Transferência Bancária'), ('DINHEIRO', 'Dinheiro')], max_length=10, null=True, verbose_name='Forma Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome_cobriu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome de Quem Cobriu'),
        ),
    ]
