# Generated by Django 6.0 on 2026-05-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_fornecedor_options_alter_tiposervico_options_and_more'),
        ('workflow', '0009_alter_despesa_dados_bancarios_pagto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='colaborador_faltou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faltas_workflow', to='cadastros.colaborador', verbose_name='Quem Faltou'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='fim_cobertura',
            field=models.DateField(blank=True, null=True, verbose_name='Cob Fim'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='inicio_cobertura',
            field=models.DateField(blank=True, null=True, verbose_name='Cob Início'),
        ),
    ]
