# Generated by Django 6.0 on 2026-05-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_despesa_colaborador_faltou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante (Upload)'),
        ),
    ]
