# Generated by Django 6.0 on 2026-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alter_despesa_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='justificativa_retorno',
            field=models.TextField(blank=True, verbose_name='Justificativa / Questionamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_COMERCIAL', 'Aguardando Comercial'), ('AGUARDANDO_ADM', 'Aguardando Administrativo'), ('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador'), ('PAGO', 'Pago / Finalizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_RH', max_length=20, verbose_name='Status Atual'),
        ),
    ]
