# Generated by Django 6.0 on 2026-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_add_justificativa_retorno_e_status_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data/Hora da Solicitação'),
        ),
    ]
