# Generated by Django 6.0 on 2026-06-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_add_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'permissions': [('view_cloudinary_storage', 'Pode acessar armazenamento Cloudinary')], 'verbose_name': 'Workflow de Despesa', 'verbose_name_plural': 'Workflow de Despesas'},
        ),
        migrations.AlterField(
            model_name='despesa',
            name='dados_bancarios_pagto',
            field=models.TextField(blank=True, null=True, verbose_name='Dados para Depósito'),
        ),
    ]
