# Generated by Django 5.2.2 on 2026-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_add_cloudinary_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_COMERCIAL', 'Aguardando Comercial'), ('AGUARDANDO_ADM', 'Aguardando Administrativo'), ('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador'), ('PAGO', 'Pago / Finalizado'), ('CONFERIDO', 'Conferido'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_RH', max_length=20, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='logworkflow',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
