# Generated by Django 5.2.2 on 2026-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_add_status_conferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='dias_cobertura',
            field=models.TextField(blank=True, help_text='Datas separadas por vírgula: 2026-06-01,2026-06-05', verbose_name='Dias de Cobertura'),
        ),
    ]
