# Generated by Django 5.2.2 on 2026-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_add_dias_cobertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_COMERCIAL', 'Aguardando Comercial'), ('AGUARDANDO_ADM', 'Aguardando Administrativo'), ('AGUARDANDO_RH', 'Aguardando RH'), ('AGUARDANDO_FIN', 'Aguardando Financeiro'), ('DIRECIONADO_OP', 'Direcionado ao Operador')], max_length=30, unique=True, verbose_name='Status')),
                ('prazo_horas', models.PositiveIntegerField(help_text='Tempo máximo permitido neste status antes de ser considerado atraso.', verbose_name='Prazo (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de SLA',
                'verbose_name_plural': 'Configurações de SLA',
                'ordering': ['status'],
            },
        ),
        migrations.AlterField(
            model_name='despesa',
            name='dias_cobertura',
            field=models.TextField(blank=True, help_text='Dias de cobertura!', verbose_name='Dias de Cobertura'),
        ),
    ]
