# Generated by Django 5.2.2 on 2026-07-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_add_colaboradorinfo'),
        ('workflow', '0018_sla_dias_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='colaborador_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='cadastros.colaboradorinfo', verbose_name='Quem Cobriu'),
        ),
    ]
