# Generated by Django 5.2.2 on 2026-07-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_colaboradorinfo_options_and_more'),
        ('monitoramento_rh', '0003_folha_empresa_pagadora_folha_fornecedor_and_more'),
        ('workflow', '0019_add_colaborador_info_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='pagamento_folha',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_wf', to='monitoramento_rh.pagamentofolha', verbose_name='Pagamento de Folha'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor', verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_lancamento',
            field=models.CharField(choices=[('CAIXINHA', 'Caixinha'), ('SOLICITACAO', 'Solicitação'), ('EXTRA', 'Extra'), ('FOLHA', 'Folha de Pagamento')], default='CAIXINHA', max_length=20, verbose_name='Tipo'),
        ),
    ]
